[package]
name = "nasty"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "CLI tool to augment eww widgets."
repository= "https://github.com/KGB33/nasty"
readme = "README.md"


[dependencies]
anyhow = "1.0.72"
clap = { version = "4.0.14", features = ["derive"] }
ctrlc = { version = "3.0", features = ["termination"] }
reqwest = { version = "0.11.18", features = ["blocking", "json"] }
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.86"
tokio = { version = "1.21.2", features = ["full"] }
zbus = "3.2.0"
