[package]
name = "nastyd"
version = "0.1.0"
edition = "2021"

[dependencies]
dnote = {path = "../dnote"}
clap = "4.1.11"
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.86"
tokio = { version = "1.21.2", features = ["full"] }
zbus = "3.2.0"
