[package]
name = "nasty"
version = "0.1.0"
edition = "2021"

[dependencies]
dnote = {path = "../dnote"}
clap = { version = "4.0.14", features = ["derive"] }
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.86"
futures-lite = "1.12.0"
